using Flybillett.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Flybillett.Models
{
    public class DBInit : DropCreateDatabaseAlways<DBContext>
    {
        protected override void Seed(DBContext context)
        {
            var Flyreise1 = new Flyreise { fraBy = "Oslo", tilBy = "Bergen", pris = "650" };
            var Flyreise2 = new Flyreise { fraBy = "Oslo", tilBy = "Trondheim", pris = "950" };
            var Flyreise3 = new Flyreise { fraBy = "Oslo", tilBy = "Manchester", pris = "1350" };
            var Flyreise4 = new Flyreise { fraBy = "Oslo", tilBy = "Berlin", pris = "1450" };
            var Flyreise5 = new Flyreise { fraBy = "Oslo", tilBy = "Athen", pris = "2550" };
            var Flyreise6 = new Flyreise { fraBy = "Oslo", tilBy = "London", pris = "1250" };
            var Flyreise7 = new Flyreise { fraBy = "Oslo", tilBy = "Amsterdam", pris = "1950" };
            var Flyreise8 = new Flyreise { fraBy = "Oslo", tilBy = "Stockholm", pris = "1450" };
            var Flyreise9 = new Flyreise { fraBy = "Oslo", tilBy = "Stavanger", pris = "850" };
            var Flyreise10 = new Flyreise { fraBy = "Oslo", tilBy = "Paris", pris = "1250" };
            var Flyreise11 = new Flyreise { fraBy = "Oslo", tilBy = "Barcelona", pris = "1350" };
            var Flyreise12 = new Flyreise { fraBy = "Oslo", tilBy = "Madrid", pris = "1450" };            
            var Flyreise13 = new Flyreise { fraBy = "Bergen", tilBy = "Oslo", pris = "750" };
            var Flyreise14 = new Flyreise { fraBy = "Bergen", tilBy = "Trondheim", pris = "850" };
            var Flyreise15 = new Flyreise { fraBy = "Bergen", tilBy = "Manchester", pris = "1350" };
            var Flyreise16 = new Flyreise { fraBy = "Bergen", tilBy = "Berlin", pris = "1450" };
            var Flyreise17 = new Flyreise { fraBy = "Bergen", tilBy = "Athen", pris = "2450" };
            var Flyreise18 = new Flyreise { fraBy = "Bergen", tilBy = "London", pris = "1250" };
            var Flyreise19 = new Flyreise { fraBy = "Bergen", tilBy = "Amsterdam", pris = "1850" };
            var Flyreise20 = new Flyreise { fraBy = "Bergen", tilBy = "Stockholm", pris = "1450" };
            var Flyreise21 = new Flyreise { fraBy = "Bergen", tilBy = "Stavanger", pris = "550" };
            var Flyreise22 = new Flyreise { fraBy = "Bergen", tilBy = "Paris", pris = "1250" };
            var Flyreise23 = new Flyreise { fraBy = "Bergen", tilBy = "Barcelona", pris = "1950" };
            var Flyreise24 = new Flyreise { fraBy = "Bergen", tilBy = "Madrid", pris = "1450" };
            var Flyreise25 = new Flyreise { fraBy = "Trondheim", tilBy = "Oslo", pris = "650" };
            var Flyreise26 = new Flyreise { fraBy = "Trondheim", tilBy = "Bergen", pris = "850" };
            var Flyreise27 = new Flyreise { fraBy = "Trondheim", tilBy = "Manchester", pris = "1350" };
            var Flyreise28 = new Flyreise { fraBy = "Trondheim", tilBy = "Berlin", pris = "1450" };
            var Flyreise29 = new Flyreise { fraBy = "Trondheim", tilBy = "Athen", pris = "2350" };
            var Flyreise30 = new Flyreise { fraBy = "Trondheim", tilBy = "London", pris = "1250" };
            var Flyreise31 = new Flyreise { fraBy = "Trondheim", tilBy = "Amsterdam", pris = "1650" };
            var Flyreise32 = new Flyreise { fraBy = "Trondheim", tilBy = "Stockholm", pris = "1450" };
            var Flyreise33 = new Flyreise { fraBy = "Trondheim", tilBy = "Stavanger", pris = "950" };
            var Flyreise34 = new Flyreise { fraBy = "Trondheim", tilBy = "Paris", pris = "1250" };
            var Flyreise35 = new Flyreise { fraBy = "Trondheim", tilBy = "Barcelona", pris = "1950" };
            var Flyreise36 = new Flyreise { fraBy = "Trondheim", tilBy = "Madrid", pris = "1450" };
            var Flyreise37 = new Flyreise { fraBy = "Manchester", tilBy = "Oslo", pris = "650" };
            var Flyreise38 = new Flyreise { fraBy = "Manchester", tilBy = "Bergen", pris = "850" };
            var Flyreise39 = new Flyreise { fraBy = "Manchester", tilBy = "Trondheim", pris = "1350" };
            var Flyreise40 = new Flyreise { fraBy = "Manchester", tilBy = "Berlin", pris = "1450" };
            var Flyreise41 = new Flyreise { fraBy = "Manchester", tilBy = "Athen", pris = "2350" };
            var Flyreise42 = new Flyreise { fraBy = "Manchester", tilBy = "London", pris = "1250" };
            var Flyreise43 = new Flyreise { fraBy = "Manchester", tilBy = "Amsterdam", pris = "1650" };
            var Flyreise44 = new Flyreise { fraBy = "Manchester", tilBy = "Stockholm", pris = "1450" };
            var Flyreise45 = new Flyreise { fraBy = "Manchester", tilBy = "Stavanger", pris = "950" };
            var Flyreise46 = new Flyreise { fraBy = "Manchester", tilBy = "Paris", pris = "1250" };
            var Flyreise47 = new Flyreise { fraBy = "Manchester", tilBy = "Barcelona", pris = "1950" };
            var Flyreise48 = new Flyreise { fraBy = "Manchester", tilBy = "Madrid", pris = "1450" };
            context.Flyreise.Add(Flyreise1);
            context.Flyreise.Add(Flyreise2);
            context.Flyreise.Add(Flyreise3);
            context.Flyreise.Add(Flyreise4);
            context.Flyreise.Add(Flyreise5);
            context.Flyreise.Add(Flyreise6);
            context.Flyreise.Add(Flyreise7);
            context.Flyreise.Add(Flyreise8);
            context.Flyreise.Add(Flyreise9);
            context.Flyreise.Add(Flyreise10);
            context.Flyreise.Add(Flyreise11);
            context.Flyreise.Add(Flyreise12);
            context.Flyreise.Add(Flyreise13);
            context.Flyreise.Add(Flyreise14);
            context.Flyreise.Add(Flyreise15);
            context.Flyreise.Add(Flyreise16);
            context.Flyreise.Add(Flyreise17);
            context.Flyreise.Add(Flyreise18);
            context.Flyreise.Add(Flyreise19);
            context.Flyreise.Add(Flyreise20);
            context.Flyreise.Add(Flyreise21);
            context.Flyreise.Add(Flyreise22);
            context.Flyreise.Add(Flyreise23);
            context.Flyreise.Add(Flyreise24);
            context.Flyreise.Add(Flyreise25);
            context.Flyreise.Add(Flyreise26);
            context.Flyreise.Add(Flyreise27);
            context.Flyreise.Add(Flyreise28);
            context.Flyreise.Add(Flyreise29);
            context.Flyreise.Add(Flyreise30);
            context.Flyreise.Add(Flyreise31);
            context.Flyreise.Add(Flyreise32);
            context.Flyreise.Add(Flyreise33);
            context.Flyreise.Add(Flyreise34);
            context.Flyreise.Add(Flyreise35);
            context.Flyreise.Add(Flyreise36);
            context.Flyreise.Add(Flyreise37);
            context.Flyreise.Add(Flyreise38);
            context.Flyreise.Add(Flyreise39);
            context.Flyreise.Add(Flyreise40);
            context.Flyreise.Add(Flyreise41);
            context.Flyreise.Add(Flyreise42);
            context.Flyreise.Add(Flyreise43);
            context.Flyreise.Add(Flyreise44);
            context.Flyreise.Add(Flyreise45);
            context.Flyreise.Add(Flyreise46);
            context.Flyreise.Add(Flyreise47);
            context.Flyreise.Add(Flyreise48);
            var Kunde1 = new Kunde { Fornavn = "Hans", Etternavn = "Olsen", Email = "olsen@mail.no"};
            var Kunde2 = new Kunde { Fornavn = "Peter", Etternavn = "Brende", Email = "brende@mail.no"};
            var Kunde3 = new Kunde { Fornavn = "Stig", Etternavn = "Hansen", Email = "hansen@mail.no"};
            var Kunde4 = new Kunde { Fornavn = "Bjarne", Etternavn = "Pettersen", Email = "pettersen@mail.no"};
            var Kunde5 = new Kunde { Fornavn = "Ole", Etternavn = "Ottosen", Email = "ottosen@mail.no"};
            var Kunde6 = new Kunde { Fornavn = "Raymond", Etternavn = "Brun", Email = "brun@mail.no"};
            var Kunde7 = new Kunde { Fornavn = "Fredrik", Etternavn = "Asaf", Email = "asaf@mail.no"};
            var Kunde8 = new Kunde { Fornavn = "Hans", Etternavn = "Johnsen", Email = "johnsen@mail.no"};
            context.Kunde.Add(Kunde1);
            context.Kunde.Add(Kunde2);
            context.Kunde.Add(Kunde3);
            context.Kunde.Add(Kunde4);
            context.Kunde.Add(Kunde5);
            context.Kunde.Add(Kunde6);
            context.Kunde.Add(Kunde7);
            context.Kunde.Add(Kunde8);
            var Admin1 = new Admin { Bruker = "admin" passord = "admin"};
            context.Admin.Add(Admin1);
            base.Seed(context);
        }
    }
}